/**
 * HTML Template Renderer for PDF Export (Text-Only)
 * NO ICONS, NO EMOJIS - Production-ready output with proper fonts
 */

import type { TripExportData } from './types.ts';
import { calculateNetSettlement } from './util.ts';

export function renderTemplate(data: TripExportData): string {
  const {
    tripId,
    tripTitle,
    subtitle,
    destination,
    startDate,
    endDate,
    coverImageUrl,
    deeplinkQrSvg,
    generatedAtLocal,
    layout,
    privacyRedaction,
    totals,
    roster,
    calendar,
    payments,
    polls,
    tasks,
    places,
    broadcasts,
    attachments,
  } = data;

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(tripTitle)} – PDF Export</title>
  <style>${getStyles()}</style>
</head>
<body>
  ${renderCoverHeader(data)}

  ${roster && roster.length > 0 && layout === 'pro' ? renderRoster(roster) : ''}
  ${calendar && calendar.length > 0 ? renderCalendar(calendar) : ''}
  ${payments && payments.length > 0 ? renderPayments(payments, totals) : ''}
  ${polls && polls.length > 0 ? renderPolls(polls) : ''}
  ${tasks && tasks.length > 0 ? renderTasks(tasks) : ''}
  ${places && places.length > 0 ? renderPlaces(places) : ''}
  ${broadcasts && broadcasts.length > 0 && layout === 'pro' ? renderBroadcasts(broadcasts) : ''}
  ${attachments && attachments.length > 0 && layout === 'pro' ? renderAttachments(attachments) : ''}

  <div class="footer-text">
    Generated by Chravel &nbsp;•&nbsp; ${escapeHtml(generatedAtLocal)} &nbsp;•&nbsp; Trip ID: ${escapeHtml(tripId)}
  </div>
</body>
</html>`;
}

function renderCoverHeader(data: TripExportData): string {
  const { tripTitle, subtitle, destination, startDate, endDate, coverImageUrl, deeplinkQrSvg } = data;
  
  const hasMeta = destination || (startDate && endDate);
  const metaText = [
    destination ? escapeHtml(destination) : null,
    startDate && endDate ? `${escapeHtml(startDate)} – ${escapeHtml(endDate)}` : null,
  ].filter(Boolean).join(' &nbsp;•&nbsp; ');

  if (coverImageUrl) {
    // Full-bleed image with gradient overlay
    return `
  <div class="cover-header" style="background-image: url('${escapeHtml(coverImageUrl)}');">
    <div class="cover-overlay">
      <div class="cover-content">
        <h1 class="cover-title">${escapeHtml(tripTitle)}</h1>
        ${subtitle ? `<p class="cover-subtitle">${escapeHtml(subtitle)}</p>` : ''}
        ${hasMeta ? `<div class="cover-meta">${metaText}</div>` : ''}
        ${deeplinkQrSvg ? `<div class="cover-qr">${deeplinkQrSvg}</div>` : ''}
      </div>
    </div>
  </div>`;
  } else {
    // Solid color banner fallback
    return `
  <div class="cover-header cover-solid">
    <div class="cover-content">
      <h1 class="cover-title">${escapeHtml(tripTitle)}</h1>
      ${subtitle ? `<p class="cover-subtitle">${escapeHtml(subtitle)}</p>` : ''}
      ${hasMeta ? `<div class="cover-meta">${metaText}</div>` : ''}
      ${deeplinkQrSvg ? `<div class="cover-qr">${deeplinkQrSvg}</div>` : ''}
    </div>
  </div>`;
  }
}

function renderRoster(roster: any[]): string {
  return `
  <section class="section">
    <h2>Roster & Contacts</h2>
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Role</th>
          <th>Email</th>
          <th>Phone</th>
        </tr>
      </thead>
      <tbody>
        ${roster.map(m => `
          <tr>
            <td>${escapeHtml(m.name)}</td>
            <td>${escapeHtml(m.role || '—')}</td>
            <td>${m.email ? escapeHtml(m.email) : '—'}</td>
            <td>${m.phone ? escapeHtml(m.phone) : '—'}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  </section>`;
}

function renderCalendar(calendar: any[]): string {
  let currentDay = '';
  let rows = '';

  calendar.forEach(item => {
    if (item.dayLabel !== currentDay) {
      currentDay = item.dayLabel;
      rows += `<div class="day-header">${escapeHtml(item.dayLabel)}</div>`;
    }
    rows += `
      <div class="event-item">
        <div><strong>${escapeHtml(item.title)}</strong> <span class="small">${escapeHtml(item.time)}</span></div>
        ${item.location ? `<div class="small">Location: ${escapeHtml(item.location)}</div>` : ''}
        ${item.notes ? `<div class="small">${escapeHtml(item.notes)}</div>` : ''}
      </div>`;
  });

  return `
  <section class="section">
    <h2>Calendar</h2>
    ${rows}
  </section>`;
}

function renderPayments(payments: any[], totals: any): string {
  const netSettlement = calculateNetSettlement(payments);
  
  return `
  <section class="section">
    <h2>Payments</h2>
    ${totals?.paymentsTotal ? `<p class="small"><strong>Total:</strong> <span class="tt">${totals.currency || 'USD'} ${totals.paymentsTotal.toFixed(2)}</span></p>` : ''}
    ${netSettlement ? `<p class="small net-settlement"><strong>Net Settlement:</strong> ${escapeHtml(netSettlement)}</p>` : ''}
    
    ${payments.map(p => `
      <div class="card">
        <div class="payment-header">
          <strong>${escapeHtml(p.title)}</strong>
          <span class="tt payment-amount">${p.currency} ${p.amount.toFixed(2)}</span>
        </div>
        <div class="small">
          Payer: ${escapeHtml(p.payer)}
          &nbsp;•&nbsp;
          Status: <span class="chip ${p.status === 'Paid' ? 'success' : (p.status === 'Overdue' ? 'danger' : 'warn')}">${p.status}</span>
          ${p.due ? ` &nbsp;•&nbsp; Due: ${escapeHtml(p.due)}` : ''}
        </div>
        ${p.split && p.split.length > 0 ? `
          <table class="table payment-split">
            <thead>
              <tr>
                <th>Member</th>
                <th class="money">Owes</th>
                <th>Status</th>
                <th>Paid Date</th>
              </tr>
            </thead>
            <tbody>
              ${p.split.map((s: any) => `
                <tr>
                  <td>${escapeHtml(s.name)}</td>
                  <td class="money">${s.owes.toFixed(2)}</td>
                  <td><span class="chip ${s.paid ? 'success' : ''}">${s.paid ? 'Paid' : 'Unpaid'}</span></td>
                  <td>${s.paid_at ? escapeHtml(s.paid_at) : '—'}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        ` : ''}
      </div>
    `).join('')}
  </section>`;
}

function renderPolls(polls: any[]): string {
  return `
  <section class="section">
    <h2>Polls</h2>
    ${polls.map(poll => `
      <div class="card">
        <strong>${escapeHtml(poll.question)}</strong>
        <table class="table poll-table">
          <thead>
            <tr>
              <th>Option</th>
              <th class="money">Votes</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            ${poll.options.map((opt: any) => `
              <tr>
                <td>${escapeHtml(opt.text)}</td>
                <td class="money">${opt.votes}</td>
                <td>${opt.winner ? '<strong>Winner</strong>' : ''}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      </div>
    `).join('')}
  </section>`;
}

function renderTasks(tasks: any[]): string {
  return `
  <section class="section">
    <h2>Tasks</h2>
    <table class="table">
      <thead>
        <tr>
          <th>Task</th>
          <th>Owner</th>
          <th>Due</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        ${tasks.map(t => `
          <tr>
            <td>${escapeHtml(t.title)}</td>
            <td>${escapeHtml(t.owner || '—')}</td>
            <td>${escapeHtml(t.due || '—')}</td>
            <td><span class="chip ${t.status === 'Done' ? 'success' : (t.status === 'Blocked' ? 'danger' : 'warn')}">${t.status}</span></td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  </section>`;
}

function renderPlaces(places: any[]): string {
  return `
  <section class="section">
    <h2>Places & Links</h2>
    ${places.map(place => `
      <div class="card place-card">
        <div class="place-header">
          <div>
            <strong>${escapeHtml(place.title)}</strong>
            <span class="small"> (${escapeHtml(place.domain)})</span>
          </div>
          ${place.qrSvg ? `<div class="qr-small">${place.qrSvg}</div>` : ''}
        </div>
        ${place.category ? `<div class="small"><strong>Category:</strong> ${escapeHtml(place.category)}</div>` : ''}
        ${place.notes ? `<div class="small">${escapeHtml(place.notes)}</div>` : ''}
        <div class="small link-url">${escapeHtml(place.url)}</div>
      </div>
    `).join('')}
  </section>`;
}

function renderBroadcasts(broadcasts: any[]): string {
  return `
  <section class="section">
    <h2>Broadcast Log</h2>
    <table class="table">
      <thead>
        <tr>
          <th>When</th>
          <th>Priority</th>
          <th>Message</th>
          <th>Read Rate</th>
        </tr>
      </thead>
      <tbody>
        ${broadcasts.map(b => `
          <tr>
            <td>${escapeHtml(b.ts)}</td>
            <td><span class="chip ${b.priority === 'High' ? 'warn' : ''}">${b.priority || 'Normal'}</span></td>
            <td>${escapeHtml(b.message)}</td>
            <td>${escapeHtml(b.readRate || '—')}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  </section>`;
}

function renderAttachments(attachments: any[]): string {
  return `
  <section class="section">
    <h2>Attachments</h2>
    <table class="table">
      <thead>
        <tr>
          <th>File</th>
          <th>Type</th>
          <th>Uploaded by</th>
          <th>Date</th>
        </tr>
      </thead>
      <tbody>
        ${attachments.map(a => `
          <tr>
            <td>${escapeHtml(a.name)}</td>
            <td>${escapeHtml(a.type)}</td>
            <td>${escapeHtml(a.uploaded_by || '—')}</td>
            <td>${escapeHtml(a.date || '—')}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  </section>`;
}

function getStyles(): string {
  return `
:root {
  --primary: #1E3A8A;
  --accent: #2563EB;
  --muted: #6B7280;
  --success: #059669;
  --warning: #D97706;
  --danger: #DC2626;
  --hair: #E5E7EB;
  --bg: #FFFFFF;
  --ink: #0F172A;
}

* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

html {
  color: var(--ink);
  font-family: 'Source Sans 3', system-ui, -apple-system, sans-serif;
  line-height: 1.35;
  -webkit-font-smoothing: antialiased;
  font-variant-ligatures: none;
  background: var(--bg);
}

body {
  max-width: 640pt;
  margin: 0 auto;
  padding: 0;
}

h1, h2, h3 {
  font-family: 'Inter', system-ui, sans-serif;
  margin: 0 0 6pt 0;
  font-weight: 700;
}

h1 {
  font-size: 24pt;
  color: var(--ink);
}

h2 {
  font-size: 16pt;
  color: var(--primary);
  margin-top: 24pt;
  margin-bottom: 12pt;
  font-weight: 700;
  text-decoration: underline;
  text-underline-offset: 3pt;
  text-decoration-thickness: 1.5pt;
}

h3 {
  font-size: 12pt;
  color: var(--muted);
  text-transform: uppercase;
  letter-spacing: 0.06em;
}

p {
  margin: 0 0 8pt 0;
  font-size: 11pt;
}

.section {
  margin: 0 24pt 24pt;
  page-break-inside: avoid;
}

.card {
  border: 1px solid var(--hair);
  border-radius: 6pt;
  padding: 10pt;
  margin-bottom: 8pt;
  page-break-inside: avoid;
}

.table {
  width: 100%;
  border-collapse: collapse;
  margin: 8pt 0;
}

.table th,
.table td {
  padding: 6pt 8pt;
  font-size: 10.5pt;
  vertical-align: top;
  text-align: left;
}

.table th {
  color: var(--muted);
  font-weight: 600;
  border-bottom: 1px solid var(--hair);
  background: #FAFAFB;
}

.table tr {
  page-break-inside: avoid;
}

.table tbody tr:nth-child(even) {
  background: #FAFAFB;
}

.money {
  text-align: right;
  font-variant-numeric: tabular-nums;
  font-family: 'Roboto Mono', monospace;
  font-size: 10pt;
}

.tt {
  font-family: 'Roboto Mono', monospace;
  font-variant-numeric: tabular-nums;
  font-size: 10pt;
}

.chip {
  display: inline-block;
  padding: 2pt 6pt;
  border-radius: 999px;
  font-size: 9pt;
  border: 1px solid var(--hair);
  color: var(--muted);
  background: #FAFAFB;
}

.chip.success {
  color: #065F46;
  border-color: #A7F3D0;
  background: #ECFDF5;
}

.chip.warn {
  color: #7C2D12;
  border-color: #FDE68A;
  background: #FFFBEB;
}

.chip.danger {
  color: #991B1B;
  border-color: #FCA5A5;
  background: #FEF2F2;
}

hr.hair {
  border: 0;
  border-top: 1px solid var(--hair);
  margin: 8pt 0;
}

.small {
  color: var(--muted);
  font-size: 10pt;
}

.pagebreak {
  page-break-before: always;
}

/* Cover Header */
.cover-header {
  position: relative;
  width: 100%;
  min-height: 280pt;
  background-size: cover;
  background-position: center;
  margin-bottom: 24pt;
}

.cover-header.cover-solid {
  background: linear-gradient(135deg, var(--primary) 0%, var(--accent) 100%);
}

.cover-overlay {
  position: absolute;
  inset: 0;
  background: linear-gradient(to bottom, rgba(0,0,0,0.4), rgba(0,0,0,0.75));
  display: flex;
  align-items: center;
  justify-content: center;
}

.cover-content {
  text-align: center;
  color: white;
  padding: 32pt;
  max-width: 520pt;
}

.cover-title {
  font-size: 32pt;
  font-weight: 700;
  margin-bottom: 12pt;
  color: white;
  text-shadow: 0 2pt 8pt rgba(0,0,0,0.3);
}

.cover-subtitle {
  font-size: 14pt;
  color: rgba(255,255,255,0.9);
  margin-bottom: 16pt;
  line-height: 1.4;
}

.cover-meta {
  font-size: 12pt;
  color: rgba(255,255,255,0.85);
  margin-top: 12pt;
  font-weight: 500;
}

.cover-qr {
  margin-top: 20pt;
  display: inline-block;
}

.cover-qr svg {
  width: 96pt;
  height: 96pt;
  filter: drop-shadow(0 4pt 12pt rgba(0,0,0,0.3));
}

/* QR Codes */
.qr-small {
  width: 48pt;
  height: 48pt;
  display: inline-block;
}

.qr-small svg {
  width: 100%;
  height: 100%;
}

/* Calendar */
.day-header {
  font-weight: 600;
  color: var(--primary);
  margin-top: 12pt;
  padding-bottom: 4pt;
  border-bottom: 1px solid var(--hair);
  font-size: 11pt;
}

.event-item {
  margin: 8pt 0 8pt 12pt;
}

/* Payments */
.payment-header {
  display: flex;
  justify-content: space-between;
  align-items: baseline;
  margin-bottom: 6pt;
}

.payment-amount {
  font-size: 12pt;
  font-weight: 600;
}

.payment-split {
  margin-top: 8pt;
  font-size: 10pt;
}

.net-settlement {
  padding: 6pt 10pt;
  background: #F0F9FF;
  border-left: 3pt solid var(--accent);
  margin: 10pt 0;
}

/* Places */
.place-card {
  display: flex;
  flex-direction: column;
  gap: 6pt;
}

.place-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
}

.link-url {
  word-break: break-all;
  color: var(--accent);
}

/* Polls */
.poll-table {
  margin-top: 8pt;
}

/* Footer */
.footer-text {
  font-size: 8pt;
  color: var(--muted);
  text-align: center;
  margin: 32pt 24pt 24pt;
  padding-top: 12pt;
  border-top: 1px solid var(--hair);
}

/* Print Optimization */
@page {
  margin: 12mm;
}

@media print {
  body {
    max-width: 100%;
    padding: 0;
  }
  
  .section {
    page-break-inside: avoid;
  }
  
  .table tr {
    page-break-inside: avoid;
  }
  
  .card {
    page-break-inside: avoid;
  }
}
  `;
}

function escapeHtml(text: string | undefined | null): string {
  if (!text) return '';
  return String(text)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
