-- Security Audit RLS Fixes (2026-02-10)
-- Addresses findings B1, B2, C9, C10, C11, D9, D10 from SECURITY-AUDIT-2026-02-09.md
-- All changes are additive (new policies replacing permissive ones) and use IF EXISTS guards

-- ============================================================================
-- B1: realtime_locations - Replace USING(true) with trip membership check
-- Previously: Any authenticated user could read ALL users' GPS coordinates
-- ============================================================================
DROP POLICY IF EXISTS "Trip participants can view locations" ON public.realtime_locations;
CREATE POLICY "Trip members can view locations"
ON public.realtime_locations FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM public.trip_members tm
    WHERE tm.trip_id = realtime_locations.trip_id
      AND tm.user_id = auth.uid()
  )
);

-- ============================================================================
-- B2: user_locations - Replace USING(true) with trip membership check
-- Previously: Any user could track any other user's location, battery, movement
-- ============================================================================
DROP POLICY IF EXISTS "Trip participants can view locations" ON public.user_locations;
CREATE POLICY "Trip members can view user locations"
ON public.user_locations FOR SELECT
USING (
  -- Users can always see their own location
  auth.uid() = user_id
  OR
  -- Trip co-members can see each other's locations
  EXISTS (
    SELECT 1 FROM public.trip_members tm1
    JOIN public.trip_members tm2 ON tm1.trip_id = tm2.trip_id
    WHERE tm1.user_id = auth.uid()
      AND tm2.user_id = user_locations.user_id
  )
);

-- ============================================================================
-- C9: Enable RLS on tables that are missing it entirely
-- ============================================================================

-- scheduled_messages: Enable RLS, scope to message owner
ALTER TABLE IF EXISTS public.scheduled_messages ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'scheduled_messages' AND policyname = 'Users manage own scheduled messages') THEN
    CREATE POLICY "Users manage own scheduled messages" ON public.scheduled_messages
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- daily_digests: Enable RLS, scope to digest recipient
ALTER TABLE IF EXISTS public.daily_digests ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'daily_digests' AND policyname = 'Users view own digests') THEN
    CREATE POLICY "Users view own digests" ON public.daily_digests
    FOR SELECT USING (auth.uid() = user_id);
  END IF;
END $$;

-- message_templates: Enable RLS, allow read of active templates
ALTER TABLE IF EXISTS public.message_templates ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'message_templates' AND policyname = 'Anyone can read active templates') THEN
    CREATE POLICY "Anyone can read active templates" ON public.message_templates
    FOR SELECT USING (is_active = true);
  END IF;
END $$;

-- email_bounces: Enable RLS, restrict to service_role only
ALTER TABLE IF EXISTS public.email_bounces ENABLE ROW LEVEL SECURITY;
-- No authenticated-role policy = only service_role can access (service_role bypasses RLS)

-- ============================================================================
-- C10: Drop overly permissive trip_chat_messages INSERT policy
-- The "Authenticated can insert trip_chat_messages" policy allows any authenticated
-- user to insert messages into ANY trip's chat. A proper trip-member-scoped policy
-- already exists from a later migration, so we just drop the permissive one.
-- PostgreSQL RLS uses OR logic for permissive policies, so the old one still applies.
-- ============================================================================
DROP POLICY IF EXISTS "Authenticated can insert trip_chat_messages" ON public.trip_chat_messages;

-- ============================================================================
-- C11: Restrict trip_embeddings write access to service_role only
-- Previously: Any authenticated user could INSERT/UPDATE/DELETE embeddings for any trip
-- Embeddings are generated by the generate-embeddings edge function using service_role
-- ============================================================================
DROP POLICY IF EXISTS "System can manage embeddings" ON public.trip_embeddings;
-- No replacement policy for authenticated role = only service_role can write
-- The existing SELECT policy scoped to trip members remains intact

-- ============================================================================
-- D9: Drop permissive security_audit_log INSERT policy
-- A later migration added a service_role-only policy, but the original permissive
-- INSERT WITH CHECK (true) still allows any user to write fake audit entries.
-- ============================================================================
DROP POLICY IF EXISTS "System can insert audit logs" ON public.security_audit_log;

-- ============================================================================
-- D10: Restrict campaign_analytics INSERT to authenticated users only
-- Previously: WITH CHECK (true) allowed even anonymous/unauthenticated inserts
-- ============================================================================
DROP POLICY IF EXISTS "analytics_insert_any" ON public.campaign_analytics;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'campaign_analytics' AND policyname = 'Authenticated users can insert analytics') THEN
    CREATE POLICY "Authenticated users can insert analytics"
    ON public.campaign_analytics FOR INSERT
    WITH CHECK (auth.uid() IS NOT NULL);
  END IF;
END $$;
