-- =====================================================
-- Upgrade trip_embeddings from VECTOR(768) to VECTOR(1536)
-- =====================================================
--
-- Migration: 20260403000000
--
-- Context: text-embedding-004 (768-dim) was shut down Jan 14, 2026.
-- Migrating to gemini-embedding-001 with outputDimensionality=1536
-- for higher quality semantic search. Existing embeddings are from
-- the dead model and must be regenerated regardless.
--
-- Post-deploy: Run generate-embeddings with forceRefresh=true for
-- all active trips to repopulate embeddings.
-- =====================================================

-- 1. Drop the IVFFlat vector index (cannot alter column type with index)
DROP INDEX IF EXISTS idx_trip_embeddings_vector;

-- 2. Drop and recreate embedding column at 1536 dimensions
--    Existing 768-dim embeddings from dead text-embedding-004 are unusable anyway
ALTER TABLE trip_embeddings DROP COLUMN IF EXISTS embedding;
ALTER TABLE trip_embeddings ADD COLUMN embedding extensions.vector(1536);

-- 3. Recreate IVFFlat index for 1536-dim vectors
CREATE INDEX IF NOT EXISTS idx_trip_embeddings_vector
  ON trip_embeddings USING ivfflat (embedding extensions.vector_cosine_ops) WITH (lists = 100);

-- 4. Update column comment
COMMENT ON COLUMN trip_embeddings.embedding IS 'Vector embedding (1536 dimensions) generated by gemini-embedding-001 model with Matryoshka reduction';
