// This file is automatically generated. Do not edit it directly.
// Build trigger: Environment variable naming fixed - VITE_SUPABASE_ANON_KEY standardized
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { isLovablePreview } from '@/utils/env';

function createSafeStorage(): Storage {
  try {
    const t = '__supabase_probe__';
    localStorage.setItem(t, '1');
    localStorage.removeItem(t);
    return localStorage;
  } catch {
    // Sandbox/3rd-party iframe or restricted mode: degrade gracefully
    const noop = {
      getItem: () => null,
      setItem: () => {},
      removeItem: () => {},
      clear: () => {},
      key: () => null,
      length: 0,
    } as unknown as Storage;
    console.warn('[Supabase] localStorage unavailable — using no-op storage (sessions will not persist).');
    return noop;
  }
}

const env = (import.meta as any)?.env ?? {};
const SUPABASE_URL = env.VITE_SUPABASE_URL || (isLovablePreview() ? 'https://jmjiyekmxwsxkfnqwyaa.supabase.co' : '');
const SUPABASE_PUBLISHABLE_KEY = env.VITE_SUPABASE_ANON_KEY || env.VITE_SUPABASE_PUBLISHABLE_KEY || (isLovablePreview()
  ? 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imptaml5ZWtteHdzeGtmbnF3eWFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MjEwMDgsImV4cCI6MjA2OTQ5NzAwOH0.SAas0HWvteb9TbYNJFDf8Itt8mIsDtKOK6QwBcwINhI'
  : '');

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const msg = 'Missing Supabase environment variables (VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY).';
  if (isLovablePreview()) {
    console.warn('[Supabase] ' + msg + ' Using built-in preview credentials.');
  } else {
    console.error('[Supabase] ' + msg);
    console.error('[Supabase] Current values:', {
      SUPABASE_URL: SUPABASE_URL || '(empty)',
      SUPABASE_PUBLISHABLE_KEY: SUPABASE_PUBLISHABLE_KEY ? '(set)' : '(empty)',
      isProduction: import.meta.env.PROD,
      mode: import.meta.env.MODE
    });
    throw new Error(msg + ' This usually means the environment variables were not available during the Vite build process. Check your deployment platform settings.');
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: createSafeStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
